# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:
  scrum-postgres:
    image: postgres
    #container_name: scrum-postgres
    #Volume mounted for database for the storage
    volumes:
      - scrum-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=elec_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    restart: unless-stopped

  #Back-end Spring Boot Application
  scrum-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: .
    container_name: elec-back
    environment:
      - DB_SERVER=scrum-postgres
      - POSTGRES_DB=elec_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on:
      - scrum-postgres

  #Fron-end Angular Application
  angular:
    image: nginx:alpine
    container_name: scrum-ui
    ports: 
      - 4200:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - C:/Users/Anass/git/angular-material/elec-front/dist/Angular/:/usr/share/nginx/html
    links:
      - scrum-app  
  #scrum-ui:
    #build: C:/Users/Anass/git/angular-material/elec-front
    #container_name: scrum-ui
    #ports:
      #- 4200:80
    #links:
      #- scrum-app

#Volumes for DB data
volumes:
  scrum-data:  
       